# Generated by Django 4.0 on 2022-01-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
